parameters:
#    demos_blog.example.class: Demos\BlogBundle\Example

services:
#    demos_blog.example:
#        class: %demos_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
